name: Test
'on':
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request: null
  workflow_dispatch: null
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref
    }}
  cancel-in-progress: true
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        version:
        - '1.11'
        - '1.12'
        - 1.13-nightly
        - nightly
        os:
        - Linux
        - Windows
        - macOS
        arch:
        - x64
        - aarch64
        exclude:
        - os: Windows
          arch: aarch64
        - os: macOS
          arch: x64
        include:
        - os: Linux
          arch: x64
          runner: ubuntu-latest
        - os: Linux
          arch: aarch64
          runner: ubuntu-latest
        - os: Windows
          arch: x64
          runner: windows-latest
        - os: macOS
          arch: aarch64
          runner: macos-latest
    steps:
    - uses: actions/checkout@v6
    - uses: julia-actions/setup-julia@v2
      with:
        version: ${{ matrix.version }}
        arch: ${{ matrix.arch }}
    - uses: julia-actions/cache@v2
    - uses: julia-actions/julia-buildpkg@v1
    - uses: julia-actions/julia-runtest@v1
